USE ad;
DROP TABLE IF EXISTS Item;
DROP TABLE IF EXISTS Seller;
DROP TABLE IF EXISTS Bidder;
DROP TABLE IF EXISTS Bids;
DROP TABLE IF EXISTS ItemCategory;
DROP TABLE IF EXISTS ItemLocation;
DROP TABLE IF EXISTS Buy_Price;
DROP TABLE IF EXISTS BidderLocation;
DROP TABLE IF EXISTS BidderCountry

