USE ad;

SET foreign_key_checks = 0;

LOAD DATA LOCAL INFILE 'Seller.csv'
INTO TABLE Seller
FIELDS TERMINATED BY '|'
LINES TERMINATED BY "\n";

LOAD DATA LOCAL INFILE 'Item.csv'
INTO TABLE Item 
FIELDS TERMINATED BY '|'
LINES TERMINATED BY "\n";

LOAD DATA LOCAL INFILE 'Bidder.csv'
INTO TABLE Bidder
FIELDS TERMINATED BY '|'
LINES TERMINATED BY "\n";


LOAD DATA LOCAL INFILE 'Bids.csv'
INTO TABLE Bids
FIELDS TERMINATED BY '|'
LINES TERMINATED BY "\n";

LOAD DATA LOCAL INFILE 'ItemCategory.csv'
INTO TABLE ItemCategory
FIELDS TERMINATED BY '|'
LINES TERMINATED BY "\n";

LOAD DATA LOCAL INFILE 'ItemLocation.csv'
INTO TABLE ItemLocation
FIELDS TERMINATED BY '|'
LINES TERMINATED BY "\n";

LOAD DATA LOCAL INFILE 'Buy_Price.csv'
INTO TABLE Buy_Price
FIELDS TERMINATED BY '|'
LINES TERMINATED BY "\n";

LOAD DATA LOCAL INFILE 'BidderLocation.csv' 
INTO TABLE BidderLocation 
FIELDS TERMINATED BY '|'
LINES TERMINATED BY "\n";

LOAD DATA LOCAL INFILE 'BidderCountry.csv' 
INTO TABLE BidderCountry 
FIELDS TERMINATED BY '|'
LINES TERMINATED BY "\n";

SET foreign_key_checks = 1;






